/**
 * 30-level campaign — blocked / crates / objectives only (engine handles powers & cascades).
 * Keep crate cells off blocked tiles. Difficulty ramps: moves↓, complexity↑.
 */
var PM = window.PM || (window.PM = {});

(function () {
  var B = {
    none: [],
    /** Center 2×2 — splits the board into quadrants */
    core4: [
      { r: 3, c: 3 },
      { r: 3, c: 4 },
      { r: 4, c: 3 },
      { r: 4, c: 4 },
    ],
    /** Four corner 2×2 clusters (like vault light) */
    vaultCorners: [
      { r: 0, c: 0 },
      { r: 0, c: 1 },
      { r: 1, c: 0 },
      { r: 0, c: 6 },
      { r: 0, c: 7 },
      { r: 1, c: 7 },
      { r: 6, c: 0 },
      { r: 7, c: 0 },
      { r: 7, c: 1 },
      { r: 6, c: 7 },
      { r: 7, c: 7 },
      { r: 7, c: 6 },
    ],
    /** Top & bottom “gates” */
    pillars: [
      { r: 0, c: 3 },
      { r: 0, c: 4 },
      { r: 7, c: 3 },
      { r: 7, c: 4 },
    ],
    /** Diagonal spine */
    spine: [
      { r: 1, c: 1 },
      { r: 2, c: 2 },
      { r: 5, c: 5 },
      { r: 6, c: 6 },
      { r: 1, c: 6 },
      { r: 2, c: 5 },
      { r: 5, c: 2 },
      { r: 6, c: 1 },
    ],
    /** Ring — outer cells except corners */
    ring: [
      { r: 0, c: 2 },
      { r: 0, c: 3 },
      { r: 0, c: 4 },
      { r: 0, c: 5 },
      { r: 7, c: 2 },
      { r: 7, c: 3 },
      { r: 7, c: 4 },
      { r: 7, c: 5 },
      { r: 2, c: 0 },
      { r: 3, c: 0 },
      { r: 4, c: 0 },
      { r: 5, c: 0 },
      { r: 2, c: 7 },
      { r: 3, c: 7 },
      { r: 4, c: 7 },
      { r: 5, c: 7 },
    ],
    /** Narrow vertical trench */
    trench: [
      { r: 0, c: 3 },
      { r: 1, c: 3 },
      { r: 2, c: 3 },
      { r: 5, c: 4 },
      { r: 6, c: 4 },
      { r: 7, c: 4 },
    ],
    /** Plus sign (thin) */
    plus: [
      { r: 3, c: 3 },
      { r: 3, c: 4 },
      { r: 4, c: 3 },
      { r: 4, c: 4 },
      { r: 2, c: 3 },
      { r: 2, c: 4 },
      { r: 5, c: 3 },
      { r: 5, c: 4 },
      { r: 3, c: 2 },
      { r: 4, c: 2 },
      { r: 3, c: 5 },
      { r: 4, c: 5 },
    ],
    /** Islands */
    isles: [
      { r: 1, c: 2 },
      { r: 1, c: 5 },
      { r: 6, c: 2 },
      { r: 6, c: 5 },
      { r: 3, c: 1 },
      { r: 4, c: 6 },
    ],
  };

  PM.LEVELS = [
    {
      id: 1,
      name: 'Glowshard Grotto',
      subtitle: 'Where the first sparks awaken',
      rows: 8,
      cols: 8,
      moves: 32,
      blocked: B.none,
      cratePositions: [],
      objectives: [{ type: 'gems', color: -1, target: 28, label: 'Any Gems' }],
    },
    {
      id: 2,
      name: 'Twin Depths',
      subtitle: 'Ruby and sapphire locked in the stone',
      rows: 8,
      cols: 8,
      moves: 28,
      blocked: B.none,
      cratePositions: [
        { r: 2, c: 2 },
        { r: 2, c: 5 },
        { r: 5, c: 2 },
        { r: 5, c: 5 },
      ],
      objectives: [
        { type: 'gems', color: 0, target: 12, label: 'Rubies' },
        { type: 'gems', color: 1, target: 12, label: 'Sapphires' },
      ],
    },
    {
      id: 3,
      name: 'Fractured Vault',
      subtitle: 'Break the seals beneath the obelisks',
      rows: 8,
      cols: 8,
      moves: 22,
      blocked: B.vaultCorners,
      cratePositions: [
        { r: 2, c: 1 },
        { r: 2, c: 6 },
        { r: 3, c: 3 },
        { r: 4, c: 4 },
        { r: 5, c: 1 },
        { r: 5, c: 6 },
      ],
      objectives: [{ type: 'crates', color: -1, target: 6, label: 'Crates' }],
    },
    {
      id: 4,
      name: 'Verdant Crossing',
      subtitle: 'Emerald paths cross amber light',
      rows: 8,
      cols: 8,
      moves: 26,
      blocked: B.pillars,
      cratePositions: [],
      objectives: [
        { type: 'gems', color: 2, target: 14, label: 'Emeralds' },
        { type: 'gems', color: 3, target: 14, label: 'Ambers' },
      ],
    },
    {
      id: 5,
      name: 'The Grand Cross',
      subtitle: 'Surprise: the center is dead — work the arms',
      rows: 8,
      cols: 8,
      moves: 24,
      blocked: B.core4,
      cratePositions: [],
      objectives: [{ type: 'gems', color: -1, target: 36, label: 'Any Gems' }],
    },
    {
      id: 6,
      name: 'Copper Freight',
      subtitle: 'Crates ride the middle rails',
      rows: 8,
      cols: 8,
      moves: 26,
      blocked: B.none,
      cratePositions: [
        { r: 3, c: 2 },
        { r: 3, c: 3 },
        { r: 3, c: 4 },
        { r: 3, c: 5 },
        { r: 4, c: 2 },
        { r: 4, c: 3 },
        { r: 4, c: 4 },
        { r: 4, c: 5 },
      ],
      objectives: [{ type: 'crates', color: -1, target: 8, label: 'Crates' }],
    },
    {
      id: 7,
      name: 'Tri-Star Junction',
      subtitle: 'Three colors, one contract',
      rows: 8,
      cols: 8,
      moves: 28,
      blocked: B.isles,
      cratePositions: [],
      objectives: [
        { type: 'gems', color: 0, target: 10, label: 'Rubies' },
        { type: 'gems', color: 1, target: 10, label: 'Sapphires' },
        { type: 'gems', color: 4, target: 10, label: 'Amethysts' },
      ],
    },
    {
      id: 8,
      name: 'Echo Ring',
      subtitle: 'The board hums around the hollow',
      rows: 8,
      cols: 8,
      moves: 25,
      blocked: B.ring,
      cratePositions: [],
      objectives: [{ type: 'gems', color: -1, target: 40, label: 'Any Gems' }],
    },
    {
      id: 9,
      name: 'Amethyst Sanctum',
      subtitle: 'Only the violet tide matters',
      rows: 8,
      cols: 8,
      moves: 24,
      blocked: B.none,
      cratePositions: [
        { r: 1, c: 3 },
        { r: 1, c: 4 },
        { r: 6, c: 3 },
        { r: 6, c: 4 },
      ],
      objectives: [{ type: 'gems', color: 4, target: 28, label: 'Amethysts' }],
    },
    {
      id: 10,
      name: 'Comet’s Gift',
      subtitle: 'Milestone: breathe — clear the field in style',
      rows: 8,
      cols: 8,
      moves: 34,
      blocked: B.none,
      cratePositions: [],
      objectives: [{ type: 'gems', color: -1, target: 48, label: 'Any Gems' }],
    },
    {
      id: 11,
      name: 'Iron & Silk',
      subtitle: 'Smash crates, feed the ruby count',
      rows: 8,
      cols: 8,
      moves: 26,
      blocked: B.pillars,
      cratePositions: [
        { r: 2, c: 2 },
        { r: 2, c: 5 },
        { r: 5, c: 2 },
        { r: 5, c: 5 },
      ],
      objectives: [
        { type: 'crates', color: -1, target: 4, label: 'Crates' },
        { type: 'gems', color: 0, target: 16, label: 'Rubies' },
      ],
    },
    {
      id: 12,
      name: 'Spine of Mirrors',
      subtitle: 'Surprise: diagonal stone — no straight shot',
      rows: 8,
      cols: 8,
      moves: 23,
      blocked: B.spine,
      cratePositions: [],
      objectives: [
        { type: 'gems', color: 2, target: 18, label: 'Emeralds' },
        { type: 'gems', color: 3, target: 18, label: 'Ambers' },
      ],
    },
    {
      id: 13,
      name: 'Sapphire Strait',
      subtitle: 'Blue flood through the trench',
      rows: 8,
      cols: 8,
      moves: 24,
      blocked: B.trench,
      cratePositions: [],
      objectives: [{ type: 'gems', color: 1, target: 32, label: 'Sapphires' }],
    },
    {
      id: 14,
      name: 'Warehouse Shift',
      subtitle: 'Ten crates — plan adjacency',
      rows: 8,
      cols: 8,
      moves: 28,
      blocked: B.core4,
      cratePositions: [
        { r: 1, c: 1 },
        { r: 1, c: 6 },
        { r: 2, c: 3 },
        { r: 2, c: 4 },
        { r: 5, c: 3 },
        { r: 5, c: 4 },
        { r: 6, c: 1 },
        { r: 6, c: 6 },
        { r: 0, c: 2 },
        { r: 0, c: 5 },
      ],
      objectives: [{ type: 'crates', color: -1, target: 10, label: 'Crates' }],
    },
    {
      id: 15,
      name: 'Quintuple Bind',
      subtitle: 'All five colors — balanced chaos',
      rows: 8,
      cols: 8,
      moves: 30,
      blocked: B.none,
      cratePositions: [],
      objectives: [
        { type: 'gems', color: 0, target: 8, label: 'Rubies' },
        { type: 'gems', color: 1, target: 8, label: 'Sapphires' },
        { type: 'gems', color: 2, target: 8, label: 'Emeralds' },
        { type: 'gems', color: 3, target: 8, label: 'Ambers' },
        { type: 'gems', color: 4, target: 8, label: 'Amethysts' },
      ],
    },
    {
      id: 16,
      name: 'The Plus Core',
      subtitle: 'Thick cross — powers love narrow lanes',
      rows: 8,
      cols: 8,
      moves: 22,
      blocked: B.plus,
      cratePositions: [],
      objectives: [{ type: 'gems', color: -1, target: 42, label: 'Any Gems' }],
    },
    {
      id: 17,
      name: 'Tightrope',
      subtitle: 'Few moves — make every swap count',
      rows: 8,
      cols: 8,
      moves: 18,
      blocked: B.none,
      cratePositions: [],
      objectives: [{ type: 'gems', color: -1, target: 38, label: 'Any Gems' }],
    },
    {
      id: 18,
      name: 'Crimson Ledger',
      subtitle: 'Rubies first — crates guard the corners',
      rows: 8,
      cols: 8,
      moves: 24,
      blocked: B.vaultCorners,
      cratePositions: [
        { r: 3, c: 2 },
        { r: 3, c: 5 },
        { r: 4, c: 2 },
        { r: 4, c: 5 },
      ],
      objectives: [
        { type: 'gems', color: 0, target: 24, label: 'Rubies' },
        { type: 'crates', color: -1, target: 4, label: 'Crates' },
      ],
    },
    {
      id: 19,
      name: 'Glacial Lock',
      subtitle: 'Sapphire surge + sealed boxes',
      rows: 8,
      cols: 8,
      moves: 26,
      blocked: B.ring,
      cratePositions: [
        { r: 3, c: 3 },
        { r: 3, c: 4 },
        { r: 4, c: 3 },
        { r: 4, c: 4 },
      ],
      objectives: [
        { type: 'gems', color: 1, target: 22, label: 'Sapphires' },
        { type: 'crates', color: -1, target: 4, label: 'Crates' },
      ],
    },
    {
      id: 20,
      name: 'The Shattered Crown',
      subtitle: 'Milestone: halfway — earn this crown',
      rows: 8,
      cols: 8,
      moves: 27,
      blocked: B.core4,
      cratePositions: [
        { r: 0, c: 3 },
        { r: 0, c: 4 },
        { r: 7, c: 3 },
        { r: 7, c: 4 },
        { r: 3, c: 0 },
        { r: 4, c: 0 },
        { r: 3, c: 7 },
        { r: 4, c: 7 },
      ],
      objectives: [{ type: 'gems', color: -1, target: 45, label: 'Any Gems' }],
    },
    {
      id: 21,
      name: 'Volcanic Shelf',
      subtitle: 'Heat and green — opposing temperaments',
      rows: 8,
      cols: 8,
      moves: 23,
      blocked: B.isles,
      cratePositions: [],
      objectives: [
        { type: 'gems', color: 0, target: 20, label: 'Rubies' },
        { type: 'gems', color: 2, target: 20, label: 'Emeralds' },
      ],
    },
    {
      id: 22,
      name: 'Clockwork Annex',
      subtitle: 'Surprise: island blocks — gems funnel oddly',
      rows: 8,
      cols: 8,
      moves: 24,
      blocked: B.isles.concat(B.core4),
      cratePositions: [],
      objectives: [{ type: 'gems', color: -1, target: 44, label: 'Any Gems' }],
    },
    {
      id: 23,
      name: 'Oubliette Row',
      subtitle: 'Twelve crates — no mercy',
      rows: 8,
      cols: 8,
      moves: 30,
      blocked: B.none,
      cratePositions: [
        { r: 2, c: 1 },
        { r: 2, c: 2 },
        { r: 2, c: 5 },
        { r: 2, c: 6 },
        { r: 5, c: 1 },
        { r: 5, c: 2 },
        { r: 5, c: 5 },
        { r: 5, c: 6 },
        { r: 3, c: 0 },
        { r: 3, c: 7 },
        { r: 4, c: 0 },
        { r: 4, c: 7 },
      ],
      objectives: [{ type: 'crates', color: -1, target: 12, label: 'Crates' }],
    },
    {
      id: 24,
      name: 'Prism Tax',
      subtitle: 'Four-way split — pay in every hue',
      rows: 8,
      cols: 8,
      moves: 26,
      blocked: B.core4,
      cratePositions: [],
      objectives: [
        { type: 'gems', color: 0, target: 12, label: 'Rubies' },
        { type: 'gems', color: 1, target: 12, label: 'Sapphires' },
        { type: 'gems', color: 3, target: 12, label: 'Ambers' },
        { type: 'gems', color: 4, target: 12, label: 'Amethysts' },
      ],
    },
    {
      id: 25,
      name: 'Obsidian Parade',
      subtitle: 'Milestone: vault ring + freight — pace yourself',
      rows: 8,
      cols: 8,
      moves: 28,
      blocked: B.ring,
      cratePositions: [
        { r: 3, c: 3 },
        { r: 3, c: 4 },
        { r: 4, c: 3 },
        { r: 4, c: 4 },
      ],
      objectives: [
        { type: 'crates', color: -1, target: 4, label: 'Crates' },
        { type: 'gems', color: -1, target: 36, label: 'Any Gems' },
      ],
    },
    {
      id: 26,
      name: 'Lumen Debt',
      subtitle: 'Triple objective — crates, any clears, and emeralds',
      rows: 8,
      cols: 8,
      moves: 25,
      blocked: B.spine,
      cratePositions: [
        { r: 0, c: 0 },
        { r: 0, c: 7 },
        { r: 7, c: 0 },
        { r: 7, c: 7 },
      ],
      objectives: [
        { type: 'crates', color: -1, target: 4, label: 'Crates' },
        { type: 'gems', color: 2, target: 16, label: 'Emeralds' },
        { type: 'gems', color: -1, target: 24, label: 'Any Gems' },
      ],
    },
    {
      id: 27,
      name: 'Starve the Void',
      subtitle: 'Low oxygen — 19 moves',
      rows: 8,
      cols: 8,
      moves: 19,
      blocked: B.plus,
      cratePositions: [],
      objectives: [{ type: 'gems', color: -1, target: 40, label: 'Any Gems' }],
    },
    {
      id: 28,
      name: 'Penultimate Gate',
      subtitle: 'Everything at once — almost home',
      rows: 8,
      cols: 8,
      moves: 26,
      blocked: B.trench.concat([
        { r: 3, c: 3 },
        { r: 4, c: 4 },
      ]),
      cratePositions: [
        { r: 2, c: 2 },
        { r: 2, c: 5 },
        { r: 5, c: 2 },
        { r: 5, c: 5 },
      ],
      objectives: [
        { type: 'crates', color: -1, target: 4, label: 'Crates' },
        { type: 'gems', color: 1, target: 14, label: 'Sapphires' },
        { type: 'gems', color: 4, target: 14, label: 'Amethysts' },
      ],
    },
    {
      id: 29,
      name: 'Beyond the Veil',
      subtitle: 'The ring tightens — one color must dominate',
      rows: 8,
      cols: 8,
      moves: 22,
      blocked: B.ring,
      cratePositions: [
        { r: 1, c: 1 },
        { r: 1, c: 6 },
        { r: 6, c: 1 },
        { r: 6, c: 6 },
        { r: 3, c: 3 },
        { r: 3, c: 4 },
        { r: 4, c: 3 },
        { r: 4, c: 4 },
      ],
      objectives: [
        { type: 'crates', color: -1, target: 8, label: 'Crates' },
        { type: 'gems', color: 0, target: 18, label: 'Rubies' },
      ],
    },
    {
      id: 30,
      name: 'Heart of the Prism',
      subtitle: 'Finale: clear the vault — you were made for this',
      rows: 8,
      cols: 8,
      moves: 24,
      blocked: B.vaultCorners,
      cratePositions: [
        { r: 2, c: 2 },
        { r: 2, c: 5 },
        { r: 3, c: 3 },
        { r: 4, c: 4 },
        { r: 5, c: 2 },
        { r: 5, c: 5 },
        { r: 1, c: 3 },
        { r: 1, c: 4 },
        { r: 6, c: 3 },
        { r: 6, c: 4 },
      ],
      objectives: [
        { type: 'crates', color: -1, target: 10, label: 'Crates' },
        { type: 'gems', color: -1, target: 30, label: 'Any Gems' },
      ],
    },
  ];

  if (PM.LEVELS.length !== 30) {
    console.warn('PRISM: expected 30 levels, got', PM.LEVELS.length);
  }
})();
